// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketService.Infrastructure.Persistence.ReportingDb;

#nullable disable

namespace TicketService.Infrastructure.Migrations.ReportingDb
{
    [DbContext(typeof(ReportingDbContext))]
    partial class ReportingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketService.Domain.Entities.EventSalesSummary", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer")
                        .HasColumnName("available_tickets");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<TimeOnly>("EventTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("event_time");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_revenue");

                    b.Property<int>("TotalTicketsSold")
                        .HasColumnType("integer")
                        .HasColumnName("total_tickets_sold");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("venue");

                    b.HasKey("EventId");

                    b.ToTable("event_sales_summaries", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TierSalesSummary", b =>
                {
                    b.Property<Guid>("PricingTierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_tier_id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_available");

                    b.Property<int>("QuantitySold")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_sold");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("revenue");

                    b.Property<string>("TierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tier_name");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("total_quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("PricingTierId");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_tier_sales_summaries_event_id");

                    b.ToTable("tier_sales_summaries", (string)null);
                });

            modelBuilder.Entity("TicketService.Domain.Entities.TierSalesSummary", b =>
                {
                    b.HasOne("TicketService.Domain.Entities.EventSalesSummary", "EventSalesSummary")
                        .WithMany("TierSummaries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventSalesSummary");
                });

            modelBuilder.Entity("TicketService.Domain.Entities.EventSalesSummary", b =>
                {
                    b.Navigation("TierSummaries");
                });
#pragma warning restore 612, 618
        }
    }
}
